hoakg2000/teamhr

- src/main/java/com/tma/teamhr/config/DispatcherServletCustomConfiguration.java
- src/main/java/com/tma/teamhr/config/JPAConfig.java
- src/main/java/com/tma/teamhr/config/RestExceptionHandler.java
Import dependency
Config JPA
Config validation response
Connecting database
> [TM-5]: config project

- src/main/java/com/tma/teamhr/config/DispatcherServletCustomConfiguration.java
- src/main/java/com/tma/teamhr/config/JPAConfig.java
- src/main/java/com/tma/teamhr/config/RestExceptionHandler.java
- src/main/java/com/tma/teamhr/model/Article.java
- src/main/java/com/tma/teamhr/model/CheckList.java
- src/main/java/com/tma/teamhr/model/ColumnType.java
- src/main/java/com/tma/teamhr/model/Columnn.java
- src/main/java/com/tma/teamhr/model/Dev.java
- src/main/java/com/tma/teamhr/model/Row.java
- src/main/java/com/tma/teamhr/model/Skill.java
- src/main/java/com/tma/teamhr/model/Team.java
- team
- dev
- skill
- column_type
- column
- row
- checklist
- article
> [TM-3]: create models

- src/main/java/com/tma/teamhr/DTO/RequestDTO/ArticleRequsetDTO.java
- src/main/java/com/tma/teamhr/DTO/RequestDTO/ChecklistRequestDTO.java
- src/main/java/com/tma/teamhr/DTO/RequestDTO/ColumnRequestDTO.java
- src/main/java/com/tma/teamhr/DTO/RequestDTO/DevRequestDTO.java
- src/main/java/com/tma/teamhr/DTO/RequestDTO/RowRequestDTO.java
- src/main/java/com/tma/teamhr/DTO/RequestDTO/SkillRequestDTO.java
- src/main/java/com/tma/teamhr/DTO/RequestDTO/TeamRequestDTO.java
Create request DTO classes:
- ArticleRequestDTO
- ChecklistRequestDTO
- ColumnRequestDTO
- RowRequestDTO
- DevRequestDTO
- TeamRequestDTO
- SkillRequestDTO
> [TM-16]: create request DTO classes

- src/main/java/com/tma/teamhr/DTO/RequestDTO/SkillRequestDTO.java
- src/main/java/com/tma/teamhr/DTO/ResponseDTO/ResponseDTO.java
- src/main/java/com/tma/teamhr/DTO/ResponseDTO/SkillResponseDTO.java
- src/main/java/com/tma/teamhr/controller/SkillController.java
- src/main/java/com/tma/teamhr/model/Skill.java
- src/main/java/com/tma/teamhr/repository/SkillRepository.java
- src/main/java/com/tma/teamhr/service/SkillService.java
- src/main/java/com/tma/teamhr/service/impl/SkillServiceImpl.java
- src/main/java/com/tma/teamhr/utils/message.java
1. Create model Skill: an instance of table skill in database
2. Create SkillRequestDTO: using to check validate request data when updating and creating skill
3. Create SkillResponseDTO: convert Skill entity to response object.
4. Create SkillController -> mapping api [post] /api/v1/skills/get -> response skillList
5. Create SKillService -> method getAll() -> get list Skill -> Convert Entity to DTO and return List DTO.
6. Create SkillRepository -> implement CrudRepository -> using to query from database
> [TM-26] implement api get all skill record

- src/main/java/com/tma/teamhr/DTO/RequestDTO/SkillRequestDTO.java
- src/main/java/com/tma/teamhr/DTO/ResponseDTO/ResponseDTO.java
- src/main/java/com/tma/teamhr/DTO/ResponseDTO/SkillResponseDTO.java
- src/main/java/com/tma/teamhr/controller/SkillController.java
- src/main/java/com/tma/teamhr/model/Skill.java
- src/main/java/com/tma/teamhr/repository/SkillRepository.java
- src/main/java/com/tma/teamhr/service/SkillService.java
- src/main/java/com/tma/teamhr/service/impl/SkillServiceImpl.java
- src/main/java/com/tma/teamhr/utils/message.java
1. SkillController: add create()
- Check valid SkillRequestDTO
- mapping /api/v1/skills/create
- return SkillResponseDTO
2. SkillService: add create(SkillRequestDTO)
- Check if duplicate name
- Convert requestDTO to Entity
- return responseDTO 
3. SkillRepository: add FindByName()
*Checkout from TM26
> [TM-28] implement api create new Skill object

- src/main/java/com/tma/teamhr/controller/SkillController.java
- src/main/java/com/tma/teamhr/service/SkillService.java
- src/main/java/com/tma/teamhr/service/impl/SkillServiceImpl.java
- src/main/java/com/tma/teamhr/utils/message.java
1. SkillController: add getById mapping /api/v1/skills/{id]/get
2. ServiceController: add getById return SkillResponseDTO
*Checkout from TM-26
> [TM-27] implement api get skill by primary key

- src/main/java/com/tma/teamhr/controller/SkillController.java
- src/main/java/com/tma/teamhr/repository/SkillRepository.java
- src/main/java/com/tma/teamhr/service/SkillService.java
- src/main/java/com/tma/teamhr/service/impl/SkillServiceImpl.java
- src/main/java/com/tma/teamhr/utils/message.java
Update id not exists
Update duplicate name
Update success
1. SkillController add update()
- Check valid SkillRequestDTO
- mapping /api/v1/skills/create
- return SkillResponseDTO
2. SkillService add update()
- Check if id exists
- Check if duplicate name
- Convert requestDTO to Entity
- return responseDTO
3. SkillRepository add findByName()
*Checkout from TM-26
> [TM-29] Implement api update Skill

- src/main/java/com/tma/teamhr/DTO/RequestDTO/TeamRequestDTO.java
- src/main/java/com/tma/teamhr/DTO/ResponseDTO/TeamResponseDTO.java
- src/main/java/com/tma/teamhr/controller/TeamController.java
- src/main/java/com/tma/teamhr/model/Team.java
- src/main/java/com/tma/teamhr/repository/TeamRepository.java
- src/main/java/com/tma/teamhr/service/TeamService.java
- src/main/java/com/tma/teamhr/service/impl/TeamServiceImpl.java
1. Create model Team: an instance of table team in database
2. Create TeamRequestDTO: 
3. using to check validate request data when updating and creating skill
4. Create TeamResponseDTO: convert team entity to response object.
5. Create TeamController method getAll():
- mapping api [post] /api/v1/skills/get
- return response skillList
6. Create TeamService - method getAll()  
- get Team list
- Convert Entity to DTO
- return List DTO.
7. Create TeamRepository -> implement CrudRepository
> [TM-20] implement api get all team records

- src/main/java/com/tma/teamhr/DTO/RequestDTO/TeamRequestDTO.java
- src/main/java/com/tma/teamhr/DTO/ResponseDTO/TeamResponseDTO.java
- src/main/java/com/tma/teamhr/controller/TeamController.java
- src/main/java/com/tma/teamhr/model/Team.java
- src/main/java/com/tma/teamhr/repository/TeamRepository.java
- src/main/java/com/tma/teamhr/service/TeamService.java
- src/main/java/com/tma/teamhr/service/impl/TeamServiceImpl.java
TeamController - getById()
- return response TeamResponseDTO
TeamService - getById()
- Query to select object Team by id
- return TeamResponseDTO object
> [TM-21] implement api get team by id

- src/main/java/com/tma/teamhr/DTO/ResponseDTO/ResponseDTO.java
- src/main/java/com/tma/teamhr/ExceptionHandler/ApiExceptionHandler.java
- src/main/java/com/tma/teamhr/ExceptionHandler/ApiRequestException.java
- src/main/java/com/tma/teamhr/controller/SkillController.java
- src/main/java/com/tma/teamhr/service/impl/SkillServiceImpl.java
Remove try-catch in controller
add try-catch around repository query throw new ApiRequestException
> [TM-26] change exception handler method and merge with main

- src/main/java/com/tma/teamhr/DTO/ResponseDTO/ResponseDTO.java
- src/main/java/com/tma/teamhr/ExceptionHandler/ApiExceptionHandler.java
- src/main/java/com/tma/teamhr/ExceptionHandler/ApiRequestException.java
Edit Model 
- int status_code -> HttpStatus statusCode
- String error -> Throwable
- add ZonedDateTime timestamp
Create package ExceptionHandler
Create ApiExceptionHandler -> handling ApiRequestException
Create ApiRequestException -> custom exception
> [TM-31] Implement exception Handler

- src/main/java/com/tma/teamhr/DTO/ResponseDTO/ResponseDTO.java
- src/main/java/com/tma/teamhr/ExceptionHandler/ApiExceptionHandler.java
- src/main/java/com/tma/teamhr/ExceptionHandler/ApiRequestException.java
- src/main/java/com/tma/teamhr/controller/SkillController.java
- src/main/java/com/tma/teamhr/service/impl/SkillServiceImpl.java
Controller: Remove try-catch
Service: Delete old try-catch and Replace with throw new ApiRequestException
> [TM-27] change exception handler method and merge with main

- src/main/java/com/tma/teamhr/DTO/ResponseDTO/ResponseDTO.java
- src/main/java/com/tma/teamhr/ExceptionHandler/ApiExceptionHandler.java
- src/main/java/com/tma/teamhr/ExceptionHandler/ApiRequestException.java
- src/main/java/com/tma/teamhr/controller/SkillController.java
- src/main/java/com/tma/teamhr/service/SkillService.java
- src/main/java/com/tma/teamhr/service/impl/SkillServiceImpl.java
Controller: Remove try-catch
Service: 
-Delete old try-catch and Replace with throw new ApiRequestException
- Add try catch around Repository query
> [TM-28] change exception handler method and merge with main

- src/main/java/com/tma/teamhr/DTO/ResponseDTO/ResponseDTO.java
- src/main/java/com/tma/teamhr/ExceptionHandler/ApiExceptionHandler.java
- src/main/java/com/tma/teamhr/ExceptionHandler/ApiRequestException.java
- src/main/java/com/tma/teamhr/controller/SkillController.java
- src/main/java/com/tma/teamhr/service/SkillService.java
- src/main/java/com/tma/teamhr/service/impl/SkillServiceImpl.java
Controller: Remove try-catch
Service:
- Replace all old Exception with ApiRequestException
- Add try catch around Repository query
> [TM-29] change exception handler method and merge with main

- src/main/java/com/tma/teamhr/controller/SkillController.java
- src/main/java/com/tma/teamhr/service/impl/SkillServiceImpl.java
Controller: Remove try-catch
Service:
- Replace all old Exception with ApiRequestException
- Add try catch around Repository query throw ApiRequestException
> [TM-30] change exception handler method and merge with main

- src/main/java/com/tma/teamhr/controller/SkillController.java
rename mapping api /{id}/delete method name from update() to delete()
SkillController - delete():
- Fix response status data type in 
- Remove try-catch
> [TM-30] fix SkillController - delete()

- src/main/java/com/tma/teamhr/controller/TeamController.java
- src/main/java/com/tma/teamhr/service/impl/TeamServiceImpl.java
TeamController: getById():
- remove try-catch
TeamServiceImpl: getById():
- change throw exception type to ApiRequestException
> TM-21 merge with main, change exception catch location

- src/main/java/com/tma/teamhr/controller/TeamController.java
- src/main/java/com/tma/teamhr/service/TeamService.java
- src/main/java/com/tma/teamhr/service/impl/TeamServiceImpl.java
Controller create()
- check validate
- call service create
Service create()
- convert requestDTO to Entity
- query insert entity
- return inserted entity
> [TM-22] implement api create new team

- src/main/java/com/tma/teamhr/controller/TeamController.java
- src/main/java/com/tma/teamhr/service/TeamService.java
- src/main/java/com/tma/teamhr/service/impl/TeamServiceImpl.java
Controller: update()
- check validation
- call update service
- 
Service update()
- convert requestDTO to Entity
- check if id exist ? throw ApiRequestException
- query insert entity
- return inserted entity
> [TM-23] implement api update team object

- src/main/java/com/tma/teamhr/controller/TeamController.java
- src/main/java/com/tma/teamhr/service/TeamService.java
- src/main/java/com/tma/teamhr/service/impl/TeamServiceImpl.java
Controller: delete
return response with message
Service delete
- throw not existed id exception
- try-catch repository query
- return true
> [TM-24] implement api delete team by id

- src/main/java/com/tma/teamhr/DTO/RequestDTO/DevRequestDTO.java
- src/main/java/com/tma/teamhr/DTO/ResponseDTO/DevResponseDTO.java
- src/main/java/com/tma/teamhr/controller/DevController.java
- src/main/java/com/tma/teamhr/model/Dev.java
- src/main/java/com/tma/teamhr/repository/DevRepository.java
- src/main/java/com/tma/teamhr/service/DevService.java
- src/main/java/com/tma/teamhr/service/impl/DevServiceImpl.java
- src/main/java/com/tma/teamhr/utils/message.java
Init class layer
Model: Dev
DTO: 
- DevResponseDTO
- DevRequestDTO
Controller: DevController
Service: DevServiceImpl
Implement api: get all /api/v1/devs/get
Controller 
- call getAll DevService's method
Service:
- Try-catch repository query
- return List<DevResponseDTO>
> [TM-32] Init dev class layer, implement api get all dev records

- src/main/java/com/tma/teamhr/controller/DevController.java
- src/main/java/com/tma/teamhr/service/DevService.java
- src/main/java/com/tma/teamhr/service/impl/DevServiceImpl.java
DevController - getById() - api : /api/v1/devs/{id}/get
- return response DevResponseDTO
DevService - getById()
- Query to select object dev by id
- return DevResponseDTO object
*Checkout from TM-32
> [TM-33] implement api get dev by id

- src/main/java/com/tma/teamhr/DTO/RequestDTO/ChecklistRequestDTO.java
- src/main/java/com/tma/teamhr/DTO/ResponseDTO/ChecklistResponseDTO.java
- src/main/java/com/tma/teamhr/controller/ChecklistController.java
- src/main/java/com/tma/teamhr/controller/TeamController.java
- src/main/java/com/tma/teamhr/model/Checklist.java
- src/main/java/com/tma/teamhr/repository/ChecklistRepository.java
- src/main/java/com/tma/teamhr/service/ChecklistService.java
- src/main/java/com/tma/teamhr/service/impl/ChecklistServiceImpl.java
Controller: getById() api /api/v1/checklist/{id}/get
Service getById()
- throw exception not found id
- return checklistResponseDTO
*Checkout from TM-37
> [TM-38] implement api get checklist by id

- src/main/java/com/tma/teamhr/controller/DevController.java
- src/main/java/com/tma/teamhr/service/DevService.java
- src/main/java/com/tma/teamhr/service/impl/DevServiceImpl.java
- src/main/java/com/tma/teamhr/utils/message.java
> [TM-34] implement api create dev"

- src/main/java/com/tma/teamhr/controller/DevController.java
- src/main/java/com/tma/teamhr/service/DevService.java
- src/main/java/com/tma/teamhr/service/impl/DevServiceImpl.java
- src/main/java/com/tma/teamhr/utils/message.java
> [TM-36] Implement api delete dev by id

- src/main/java/com/tma/teamhr/DTO/RequestDTO/ChecklistRequestDTO.java
- src/main/java/com/tma/teamhr/controller/ChecklistController.java
- src/main/java/com/tma/teamhr/model/Checklist.java
- src/main/java/com/tma/teamhr/model/Team.java
- src/main/java/com/tma/teamhr/service/ChecklistService.java
- src/main/java/com/tma/teamhr/service/impl/ChecklistServiceImpl.java
- src/main/java/com/tma/teamhr/utils/message.java
- src/main/resources/databases.properties
Model: add RelationShip OneToOne with checklist
Request DTO: add team_id
Controller /api/v1/checklists/create
Service: create()
> [Tm 39] Implement api create new checklist

- src/main/java/com/tma/teamhr/DTO/ResponseDTO/ResponseDTO.java
- src/main/java/com/tma/teamhr/ExceptionHandler/ApiExceptionHandler.java
- src/main/java/com/tma/teamhr/ExceptionHandler/DataBaseException.java
- src/main/java/com/tma/teamhr/ExceptionHandler/EntityToDTOConvertException.java
- src/main/java/com/tma/teamhr/ExceptionHandler/NotFoundException.java
- src/main/java/com/tma/teamhr/ExceptionHandler/UniqueEntityException.java
Exceptions:
1. DataBaseException
2. EntityToDTOConvertException
3. NotFoundException
4. UniqueEntityException
ResponseDTO constructor:
1. ResponseDTO (RuntimeException e) request failed
2. ResponseDTO (Object data) request success
> [TM-47] Implement exceptions case, create ResponseDTO constructor
